## 实现多元线性回归模型

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [5]:
X.shape

(490, 13)

In [8]:
%run ../playML/model_selection.py

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, seed=666)

In [15]:
X_train

array([[1.42362e+01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.96900e+02, 2.03200e+01],
       [3.67822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.80790e+02, 1.01900e+01],
       [1.04690e-01, 4.00000e+01, 6.41000e+00, ..., 1.76000e+01,
        3.89250e+02, 6.05000e+00],
       ...,
       [6.71800e-01, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        4.30600e+01, 2.39800e+01],
       [9.59571e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.76110e+02, 2.03100e+01],
       [2.06080e-01, 2.20000e+01, 5.86000e+00, ..., 1.91000e+01,
        3.72490e+02, 1.25000e+01]])

In [16]:
X_test

array([[3.25430e-01, 0.00000e+00, 2.18900e+01, ..., 2.12000e+01,
        3.96900e+02, 1.53900e+01],
       [2.14090e-01, 2.20000e+01, 5.86000e+00, ..., 1.91000e+01,
        3.77070e+02, 3.59000e+00],
       [8.20058e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
        3.50000e+00, 1.69400e+01],
       ...,
       [5.11830e-01, 0.00000e+00, 6.20000e+00, ..., 1.74000e+01,
        3.90070e+02, 4.73000e+00],
       [1.53800e-02, 9.00000e+01, 3.75000e+00, ..., 1.59000e+01,
        3.86340e+02, 3.11000e+00],
       [1.00245e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
        3.80230e+02, 1.19800e+01]])

In [17]:
y_train

array([ 7.2, 20.8, 33.2, 13.1, 39.8, 16.5, 14.9, 14.5, 26.5, 19.1, 20.1,
       30.1, 23. , 23.7, 10.5, 23.1, 37.3, 13.9, 15.6, 21.1, 32.5, 10.2,
       29. , 16.4, 10.4, 23.3, 36.4, 25. , 20.3, 33.3, 33.4, 36.2, 20.1,
       22.5, 14.4, 29.6, 48.8, 20.3, 24.7, 21.4, 17.1,  5. , 26.7, 24. ,
       26.6, 22. , 10.2, 37. , 22.8, 20. , 19.8, 18.5, 24.8, 21.2, 27.5,
       21.2, 19.2, 30.7, 27.1, 24.5, 18.2, 32.2, 26.4,  9.7, 21. , 18.1,
       18.6, 17.1, 20. , 19.9, 23.5, 27.5, 42.3, 24.7, 23.8, 15. ,  8.3,
       36.1, 14.3, 21.5, 13.6, 13.8, 18.5, 18.5, 21.5, 24.4, 17.3, 16.5,
       13.6, 17.8, 24.3, 19.5, 33.8, 24.3, 23.2, 25. , 22. , 22. , 17.1,
       22.2, 22. , 20.6, 21.4,  8.7, 13.3,  7.4, 23.7, 19.4, 21.6, 19.1,
       21.7,  8.8, 11.9, 35.2, 23.1, 37.6, 26.4, 27.1, 29.1, 21.9, 15.2,
       15.3, 21.7, 18.2, 23.8, 22.6, 21.9, 23.2, 20.1, 34.9, 22.6, 22.2,
       19.4, 23.7,  8.4, 10.4, 28.7, 20.1, 20.7, 18.5, 21.8, 43.5, 22.9,
       19.3, 19.7, 24.5,  7. , 24.5, 22.9, 25. , 16

In [18]:
y_test

array([18. , 24.8, 13.5, 34.9, 23.7, 13.8, 25.1, 28.5, 15.6, 33. , 16.2,
       16.3, 29.4, 17.8, 22.2, 20.6, 13.8, 19.4, 22.5, 23.9, 12.7, 24.8,
       23.9, 20.7, 23.2, 37.9, 13.5, 22.4, 12.3, 32.7, 43.1,  8.8, 12.8,
       41.7, 19.1, 21.7, 10.5, 24. , 27. , 23.1, 11. , 18.9, 15.2, 19.7,
       19.4, 14.3, 23.3, 31. , 19.8, 22.8, 19.6, 14.9, 24.7, 15.4, 19.6,
       18.9, 23. , 10.8, 28.6, 35.4, 18.8, 23.4, 22.6,  8.3, 12.7, 26.6,
       19.8, 18.9, 29. , 19. , 13. , 22.3, 22.8, 19.5, 14.1, 28.4, 20.1,
       13.9, 12. , 33.1, 38.7, 17.5, 19.9, 20.2, 29.6, 21.2, 21.6, 23.9,
       28.1, 20.4, 24.4, 35.4, 46. , 20.4, 16. , 31.5, 44. , 21. ])

In [27]:
%run ../playML/LinearRegression.py

In [28]:
reg = LinearRegression()
reg.fit_normal(X_train, y_train)

LinearRegression()

In [29]:
reg.coef_

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [30]:
reg.interception_

34.161435496213905

In [31]:
reg.score(X_test, y_test)

0.8129802602658359