### 直观理解高斯核函数

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x = np.arange(-4, 5, 1)

In [3]:
x

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [4]:
y = np.array((x >= -1) & (x <= 2), dtype='int')

In [5]:
y

array([0, 0, 0, 1, 1, 1, 1, 0, 0])

In [6]:
plt.scatter(x[y==0], [0]*len(x[y==0]))
plt.scatter(x[y==1], [0]*len(x[y==1]))
plt.show()

In [7]:
def gaussion(x, l):
    gamma = 1.0
    return np.exp(-gamma * (x - l) ** 2)

In [8]:
l1, l2 = -1, 1

X_new = np.empty((len(x), 2))
for i, data in enumerate(x):
    X_new[i, 0] = gaussion(data, l1)
    X_new[i, 1] = gaussion(data, l2)

In [9]:
X_new

array([[1.23409804e-04, 1.38879439e-11],
       [1.83156389e-02, 1.12535175e-07],
       [3.67879441e-01, 1.23409804e-04],
       [1.00000000e+00, 1.83156389e-02],
       [3.67879441e-01, 3.67879441e-01],
       [1.83156389e-02, 1.00000000e+00],
       [1.23409804e-04, 3.67879441e-01],
       [1.12535175e-07, 1.83156389e-02],
       [1.38879439e-11, 1.23409804e-04]])

In [10]:
plt.scatter(X_new[y==0, 0], X_new[y==0, 1])
plt.scatter(X_new[y==1, 0], X_new[y==1, 1])
plt.show()