# 1.Array(数组)
- rank: 数组的纬度

In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [6]:
type(a)

numpy.ndarray

In [7]:
# 查看数组纬度
a.shape

(3,)

In [8]:
# 重置数组纬度
a = a.reshape([1, -1])

In [9]:
a

array([[1, 2, 3]])

In [10]:
a.shape

(1, 3)

In [11]:
a = np.array([1, 2, 3, 4, 5, 6])

In [12]:
a.shape

(6,)

In [13]:
a = a.reshape(2, -1)

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a.shape

(2, 3)

In [16]:
a = a.reshape(-1, 2)

In [17]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a.shape

(3, 2)

In [19]:
a[2,0]

5

In [20]:
a[2,0] = 55

In [21]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

# 2.创建数组的方法
1. zeros：创建全为0的数组（向量、矩阵）
2. ones：创建全为1的数组（向量、矩阵）
3. full: 创建自定义的全部为某个值的数组（向量、矩阵）
4. eye: 创建单位矩阵
5. random.random：创建随机0-1之间的随机数组（向量、矩阵）

## 1.zeros

In [22]:
a = np.zeros((3, 3))

In [23]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 2.ones

In [24]:
a = np.ones((3, 3))

In [25]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 3.full

In [26]:
a = np.full((3,3),0)

In [27]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [28]:
a = np.full((2,3),3)

In [29]:
a

array([[3, 3, 3],
       [3, 3, 3]])

## 4.eye

In [30]:
a = np.eye(3)

In [31]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5.random.random

In [32]:
a = np.random.random((3, 4))

In [33]:
a

array([[0.99447237, 0.88033311, 0.15935298, 0.20994273],
       [0.01330442, 0.84244046, 0.33488977, 0.55843254],
       [0.03166977, 0.16768554, 0.17347492, 0.03253033]])

## 6.indexing

In [35]:
# 创建一个3 * 4 数组
a = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [38]:
# a [行开始:行结束, 列开始:列结束]
# -是倒数
# 取倒数第二行到最后，第一列到第三列（不包含第三列）
a[-2:, 1:3]

array([[ 6,  7],
       [10, 11]])

In [39]:
# 错误的写法
a[-2:][1:3]

array([[ 9, 10, 11, 12]])

In [40]:
# 取第1行，倒数第二个元素
a[1, -2]

7

In [41]:
a.shape

(3, 4)

In [42]:
# 截取数组
b = a[-2:,1:3]

In [43]:
# b的维度
b.shape

(2, 2)

In [45]:
b = a[2, 1:3]

In [46]:
b

array([10, 11])

In [47]:
b.shape

(2,)

In [48]:
b = a[1,2]

In [49]:
b

7

In [50]:
b.shape

()

In [51]:
b = a[2,1:3]

In [52]:
b.shape

(2,)

In [53]:
b = a[2:3,1:3]

In [54]:
b

array([[10, 11]])

In [55]:
b.shape

(1, 2)

In [56]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
# 对某些值相加, 对二列加10
a[np.arange(3), 1] += 10

In [58]:
a

array([[ 1, 12,  3,  4],
       [ 5, 16,  7,  8],
       [ 9, 20, 11, 12]])

In [59]:
# 生成[0 - 3)数组，前闭后开
np.arange(3)

array([0, 1, 2])

In [60]:
# 生成[3, 7) 前闭后开
np.arange(3, 7)

array([3, 4, 5, 6])

In [61]:
# 对二列加10
a[np.arange(3), [1, 1, 1]] += 10

In [62]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

In [67]:
# 对二列加10
a[[0, 1, 2], [1, 1, 1]] -= 10

In [68]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

In [69]:
# 判断哪些列大于10
result_index = a > 10

In [70]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [71]:
# 取出大于10的数据
a[result_index]

array([32, 36, 40, 11, 12])

In [73]:
# 简化写法
a[a > 10]

array([32, 36, 40, 11, 12])

## 7.元素的数据类型

In [74]:
# 自动推到数据类型：int32
a = np.array([1, 2])

In [75]:
a.dtype

dtype('int32')

In [76]:
# 自动推到数据类型：float64
a = np.array([1.1, 2.2])

In [77]:
a.dtype

dtype('float64')

In [78]:
# 会向上进
a = np.array([1.1, 2])

In [79]:
a.dtype

dtype('float64')

In [80]:
a = np.array([1.1, 2.2])

In [81]:
a.dtype

dtype('float64')

In [98]:
# 指定后会自动去掉小数
a = np.array([1.1, 2.2], dtype=np.int64)

In [90]:
a

array([1, 2], dtype=int64)

In [89]:
a.dtype

dtype('int64')

In [91]:
a = np.array([1.1, 2.2])

In [95]:
a

array([1.1, 2.2])

In [99]:
# 强制指定
b = np.array(a, dtype=np.int64)

In [94]:
b

array([1, 2], dtype=int64)

## 8.数学运算与常用函数

In [100]:
# 定义数组a
a = np.array([
    [1, 2],
    [3, 4]
])

In [101]:
# 定义数组b
b = np.array([
    [5, 6],
    [6, 5]
])

In [102]:
# a 和 b 对应位置相加
a + b

array([[6, 8],
       [9, 9]])

In [103]:
# NumPy中的 a + b
np.add(a, b)

array([[6, 8],
       [9, 9]])

In [104]:
# a 和 b 对应位置相减
a - b

array([[-4, -4],
       [-3, -1]])

In [105]:
# NumPy中的 a - b
np.subtract(a, b)

array([[-4, -4],
       [-3, -1]])

In [106]:
# a 和 b 对应位置相乘, 并不是矩阵的乘法操作
a * b

array([[ 5, 12],
       [18, 20]])

In [107]:
# NumPy中的 a * b, 并不是矩阵的乘法操作
np.multiply(a, b)

array([[ 5, 12],
       [18, 20]])

In [108]:
# a 和 b 对应位置相除
a / b

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [109]:
# NumPy中的 a / b
np.divide(a, b)

array([[0.2       , 0.33333333],
       [0.5       , 0.8       ]])

In [111]:
# 每个元素开方
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [113]:
# 数组a
a

array([[1, 2],
       [3, 4]])

In [114]:
# 定义数组b
b = np.array([
    [9, 12, 15],
    [19, 26, 33]
])

In [115]:
# 矩阵的乘法操作
a.dot(b)

array([[ 47,  64,  81],
       [103, 140, 177]])

In [116]:
# NumPy中矩阵乘法
np.dot(a, b)

array([[ 47,  64,  81],
       [103, 140, 177]])

In [117]:
# 矩阵的乘法，要求a的列数必须等于b的行数，否则无法相乘
np.dot(b, a)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## 9. 常用函数

#### 9.1 sum: 求和

In [120]:
a

array([[1, 2],
       [3, 4]])

In [121]:
# 对数组数据进行求和
np.sum(a)

10

In [122]:
# 对数组中的列进行求和，axis=0对列
np.sum(a, axis=0)

array([4, 6])

In [124]:
# 对数据中行进行求和，axis=1对行
np.sum(a, axis=1)

array([3, 7])

#### 9.2 mean: 求平均值

In [128]:
a

array([[1, 2],
       [3, 4]])

In [126]:
# 对数组中所有元素求平均值
np.mean(a)

2.5

In [127]:
# 对数组中的列进行求平均值，axis=0对列
np.mean(a, axis=0)

array([2., 3.])

In [129]:
# 对数据中行进行求平均值，axis=1对行
np.mean(a, axis=1)

array([1.5, 3.5])

#### 9.3 uniform: 生成指定范围的随机数值

In [130]:
np.random.uniform(3, 4)

3.488449620447292

In [131]:
np.random.uniform(1, 100)

80.38434132882178

#### 9.4 tile: 将一个数组，作为一个元素重复指定的次数

In [132]:
a

array([[1, 2],
       [3, 4]])

In [133]:
# 行不重复，列上重复两次
np.tile(a, (1, 2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [135]:
# 行重复两次，列不重复
np.tile(a, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [137]:
# 行重复两次，列重复3次
np.tile(a, (2, 3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

#### 9.5 argsort: 对数组中元素进行排序， 返回每一行排序结果的下标

In [138]:
a = np.array([
    [3, 6, 4, 11],
    [5, 10, 1, 3]
])

In [141]:
# 返回每一行排序结果的下标，从小到大
a.argsort()

array([[0, 2, 1, 3],
       [2, 3, 0, 1]], dtype=int64)

In [146]:
# axis=0 对每一列从小到大排序，是 列 拍序注意
a.argsort(axis=0)

array([[0, 0, 1, 1],
       [1, 1, 0, 0]], dtype=int64)

#### 9.6 T / transpose: 矩阵转置（行变列，列变行）

In [147]:
a

array([[ 3,  6,  4, 11],
       [ 5, 10,  1,  3]])

In [149]:
# 矩阵转置
a.T

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

In [151]:
# NumPy 矩阵转置
np.transpose(a)

array([[ 3,  5],
       [ 6, 10],
       [ 4,  1],
       [11,  3]])

## 10.广播

In [153]:
a = np.array([
    [1, 2, 3],
    [2, 3, 4],
    [12, 23, 44],
    [2, 2, 2]
])

In [154]:
b = np.array([1, 2, 3])

In [156]:
for i in range(4):
    a[i, :] += b

In [157]:
a

array([[ 2,  4,  6],
       [ 3,  5,  7],
       [13, 25, 47],
       [ 3,  4,  5]])

In [158]:
a + np.tile(b, (4, 1))

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 27, 50],
       [ 4,  6,  8]])

In [160]:
# 可以将不同维度数组相加，NumPy会自动广播转化相同的维度
# NumPy 广播, 会在缺失纬度和数值唯一的维度上进行
a + b

array([[ 3,  6,  9],
       [ 4,  7, 10],
       [14, 27, 50],
       [ 4,  6,  8]])