## 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [3]:
iris = datasets.load_iris()

In [4]:
X = iris.data
y = iris.target

In [5]:
X.shape

(150, 4)

In [6]:
y.shape

(150,)

### train_test_split

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
shuffle_index = np.random.permutation(len(X))

In [9]:
shuffle_index

array([ 94,  29,  18, 138,   6,  72,  95, 107,  65,  80, 101,  42,  12,
        21,  41,  19, 106,  17,  38,  24,  88,  86, 100,  67,  75, 148,
         3,  83,  20, 139, 110, 114,  68,  98, 149,  36,  32,   9, 115,
       105, 131,  76, 128, 103,  96,  28,   1,  37,  69,  61,  49,  64,
       145,  59, 119,   4,  85,  16,  54,  27,  74, 124, 141, 127, 108,
        25,  66, 129,  52,  10, 146, 120,  22,   2, 116,  90,  48,  55,
       136,  15, 140,  35,  89,  84,  14, 121,  92,  47,  53, 147,  13,
        78,  46,   8, 111, 135,  70,  40,  87, 130, 123, 134, 117,  62,
        31,  73, 126, 109, 102,  51,  99, 143,  30,  91,  57,  93,  97,
        71,  43,  79,  50,  44,  56, 104,  26,  45, 118,  77, 144, 132,
        11,   5,  63, 133, 125,  60,   7,   0, 122, 137,  58,  82,  81,
       142, 112,  39,  33, 113,  23,  34])

In [11]:
test_ratio = 0.2
test_size = int(len(X) * test_ratio)

In [12]:
test_size

30

In [15]:
test_indexes = shuffle_index[:test_size]
train_indexes = shuffle_index[test_size:]

In [16]:
test_indexes

array([ 94,  29,  18, 138,   6,  72,  95, 107,  65,  80, 101,  42,  12,
        21,  41,  19, 106,  17,  38,  24,  88,  86, 100,  67,  75, 148,
         3,  83,  20, 139])

In [17]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [18]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [19]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


## 使用我们的算法

In [21]:
%run ../kNN/model_selection.py

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [26]:
%run ../kNN/kNN.py

In [27]:
my_knn_clf = KNNClassifier(k=3)

In [28]:
my_knn_clf.fit(X_train, y_train)

KNN(K=3)

In [29]:
y_predict = my_knn_clf.predict(X_test)

In [30]:
y_predict

array([2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2, 1, 2, 1, 0, 2, 1, 2, 1, 2, 0,
       1, 2, 1, 2, 2, 0, 1, 2])

In [31]:
y_test

array([2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2, 1, 2, 1, 0, 2, 1, 2, 1, 2, 0,
       1, 2, 1, 2, 2, 0, 1, 2])

In [32]:
sum(y_predict == y_test)

29

In [33]:
sum(y_predict == y_test) / len(y_test)

0.9666666666666667

### sklearn中的train_test_split

In [34]:
from sklearn.model_selection import train_test_split

In [38]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [39]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [37]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)
