# 调试梯度下降
- 因为如果梯度下降计算错误，程序是不会抛出异常的，所以我们不知道计算是否正确，使用这种方法可以调试梯度计算出的值。

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(666)
X = np.random.random(size = (1000, 10))

In [3]:
X

array([[0.70043712, 0.84418664, 0.67651434, ..., 0.04881279, 0.09992856,
        0.50806631],
       [0.20024754, 0.74415417, 0.192892  , ..., 0.11285765, 0.11095367,
        0.24766823],
       [0.0232363 , 0.72732115, 0.34003494, ..., 0.25913185, 0.58381262,
        0.32569065],
       ...,
       [0.88593917, 0.49480495, 0.32095669, ..., 0.50598273, 0.86447115,
        0.31128276],
       [0.81051618, 0.87890841, 0.47112617, ..., 0.37299025, 0.81523744,
        0.31074351],
       [0.75052272, 0.98612317, 0.44421196, ..., 0.26679141, 0.34224855,
        0.02366081]])

In [4]:
true_theta = np.arange(1, 12, dtype=float)

In [6]:
X_b = np.hstack([np.ones((len(X), 1)), X])
y = X_b.dot(true_theta) + np.random.normal(size=1000)

In [7]:
X.shape

(1000, 10)

In [8]:
y.shape

(1000,)

In [9]:
true_theta

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
def J(theta, X_b, y):
    try:
        return np.sum((y - X_b.dot(theta))** 2) / len(X_b)
    except:
        return float('inf')

In [12]:
def dJ_math(theta, X_b, y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2. / len(y)

In [14]:
def dJ_debug(theta, X_b, y, epsilon=0.01):
    res = np.empty(len(theta))
    for i in range(len(theta)):
        theta_1 = theta.copy()
        theta_1[i] += epsilon
        theta_2 = theta.copy()
        theta_2[i] -= epsilon
        res[i] = (J(theta_1, X_b, y) - J(theta_2, X_b, y)) / (2 * epsilon)
    return res

In [15]:
def gradient_descent(dJ, X_b, y, initial_theta, eta, n_iters=1e4, epsilon=1e-8):
    theta = initial_theta
    i_iter = 0
    while i_iter < n_iters:
        gradient = dJ(theta, X_b, y)
        last_theta = theta
        theta = theta - eta * gradient

        if abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon:
            break

        i_iter += 1

    return theta

In [18]:
X_b = np.hstack([np.ones((len(X), 1)), X])
initial_theta = np.zeros(X_b.shape[1])
eta = 0.01

%time theta = gradient_descent(dJ_debug, X_b, y, initial_theta, eta)
theta

Wall time: 3.05 s


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [19]:
%time theta = gradient_descent(dJ_math, X_b, y, initial_theta, eta)
theta

Wall time: 577 ms


array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])