In [1]:
import numpy as np

In [2]:
np.__version__

'1.15.1'

## Python List的特点

In [5]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [8]:
L[5] = "Machine Learning"
L

[0, 1, 2, 3, 4, 'Machine Learning', 6, 7, 8, 9]

In [9]:
import array

In [11]:
ary = array.array('i', [i for i in range(10)])

In [12]:
ary

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
ary[5]

5

In [14]:
ary[5] = 100

In [15]:
ary

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [16]:
ary[5] = "Machine Learning"

TypeError: an integer is required (got type str)

## np.array

In [17]:
npAry = np.array([i for i in range(10)])
npAry

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
npAry[5]

5

In [19]:
npAry[5] = 100
npAry

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [20]:
npAry[5] = "Machine Learning"

ValueError: invalid literal for int() with base 10: 'Machine Learning'

In [21]:
npAry.dtype

dtype('int32')

In [22]:
npAry2 = np.array([1, 2, 3, 4.5])

In [23]:
npAry2.dtype

dtype('float64')

## 其他创建numpy.array的方法

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.zeros(shape=(3, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.full(shape=(3, 5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [32]:
np.full(fill_value=666, shape=(3, 5))

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arange

In [33]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [34]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
[i for i in range(0, 20, 0.2)]

TypeError: 'float' object cannot be interpreted as an integer

In [36]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [37]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

## linspace: 从0-20之前截出等长的10个数

In [39]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [40]:
np.linspace(0, 20, 11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [41]:
np.random.randint(0, 10)

5

In [42]:
np.random.randint(0, 10, 10)

array([7, 3, 0, 5, 3, 6, 6, 0, 2, 7])

In [43]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
np.random.randint(4, 8, size = 10)

array([6, 6, 7, 7, 7, 5, 7, 6, 6, 6])

In [46]:
np.random.randint(4, 8, size = (3, 5))

array([[6, 7, 5, 7, 6],
       [7, 4, 7, 4, 4],
       [6, 5, 4, 5, 4]])

In [48]:
# 指定随机种子
np.random.seed(666)

In [49]:
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [50]:
np.random.seed(666)
np.random.randint(4, 8, size = (3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [51]:
# 默认生成 0 - 1
np.random.random()

0.2811684913927954

In [52]:
np.random.random(10)

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [53]:
np.random.random((3, 5))

array([[0.76741234, 0.95323137, 0.29097383, 0.84778197, 0.3497619 ],
       [0.92389692, 0.29489453, 0.52438061, 0.94253896, 0.07473949],
       [0.27646251, 0.4675855 , 0.31581532, 0.39016259, 0.26832981]])

In [54]:
np.random.normal()

0.7760516793129695

In [55]:
np.random.normal(10, 100)

128.06359754812632

In [56]:
np.random.normal(0, 1, size = (3, 5))

array([[ 0.06102404,  1.07856138, -0.79783572,  1.1701326 ,  0.1121217 ],
       [ 0.03185388, -0.19206285,  0.78611284, -1.69046314, -0.98873907],
       [ 0.31398563,  0.39638567,  0.57656584, -0.07019407,  0.91250436]])

In [57]:
np.random.normal?

In [58]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap