## 聚合操作

In [1]:
import numpy as np
L = np.random.random(100)

In [2]:
L

array([0.12850169, 0.53128322, 0.73991791, 0.1916331 , 0.63107507,
       0.38685406, 0.69134261, 0.99143282, 0.0187335 , 0.82309245,
       0.06354335, 0.83376855, 0.7448266 , 0.832266  , 0.9521209 ,
       0.31530607, 0.19818857, 0.9544656 , 0.85193453, 0.34812505,
       0.79610797, 0.09357135, 0.69434842, 0.42883523, 0.1993681 ,
       0.82281908, 0.34441984, 0.17965515, 0.46407371, 0.02315929,
       0.82039406, 0.82153042, 0.44814409, 0.6239559 , 0.3293266 ,
       0.40891533, 0.66572742, 0.65670192, 0.17614384, 0.05106314,
       0.18686228, 0.21047743, 0.51125425, 0.41092333, 0.09180915,
       0.50598517, 0.37992399, 0.31556753, 0.60121168, 0.88311116,
       0.65495978, 0.92752245, 0.73569854, 0.6425741 , 0.84556984,
       0.62897415, 0.06144856, 0.35347034, 0.08205442, 0.12114475,
       0.170876  , 0.7421482 , 0.17603557, 0.59133299, 0.50871714,
       0.03476731, 0.64511701, 0.47829508, 0.92025459, 0.19376099,
       0.42585045, 0.46551431, 0.20595029, 0.58416727, 0.67910

In [3]:
sum(L)

52.11927444861518

In [4]:
np.sum(L)

52.119274448615194

In [8]:
big_array = np.random.random(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

173 ms ± 2.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.73 ms ± 62.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
np.min(big_array)

2.535855344709681e-06

In [10]:
np.max(big_array)

0.9999985282623837

In [11]:
big_array.min()

2.535855344709681e-06

In [12]:
big_array.max()

0.9999985282623837

In [13]:
big_array.sum()

499941.34983237064

In [14]:
X = np.arange(16).reshape(4, -1)

In [15]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.sum(X)

120

In [17]:
# 每一列的合，沿着列来计算
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [18]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [19]:
np.prod(X)

0

In [20]:
np.prod(X + 1)

2004189184

In [21]:
np.mean(X)

7.5

In [22]:
np.median(X)

7.5

In [28]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [26]:
np.median(v)

2.0

In [31]:
np.percentile(big_array, q=50)

0.49986910275136986

In [32]:
np.median(big_array)

0.49986910275136986

In [33]:
np.percentile(big_array, q=100)

0.9999985282623837

In [35]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

2.535855344709681e-06
0.24967461854831668
0.49986910275136986
0.7502000096579365
0.9999985282623837


In [36]:
np.var(big_array)

0.08335564730802437

In [37]:
np.std(big_array)

0.28871378094580863

In [38]:
x = np.random.normal(0, 1, size=1000000)

In [39]:
np.mean(x)

0.0007044885026770132

In [40]:
np.std(x)

0.9998740502578858

## 索引

In [41]:
np.min(x)

-5.127472640055949

In [42]:
# 获取索引值
np.argmin(x)

294736

In [43]:
x[294736]

-5.127472640055949

In [44]:
np.argmax(x)

321060

In [45]:
x[321060]

4.859589181488746

In [46]:
np.max(x)

4.859589181488746

## 排序和使用索引

In [47]:
x = np.arange(16)

In [48]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
np.random.shuffle(x)
x

array([11, 12,  6,  5, 15,  2, 14,  4,  0,  1, 13,  7,  9,  8,  3, 10])

In [50]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
x

array([11, 12,  6,  5, 15,  2, 14,  4,  0,  1, 13,  7,  9,  8,  3, 10])

In [52]:
x.sort()

In [53]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [54]:
X = np.random.randint(10, size=(4, 4))

In [55]:
X

array([[5, 8, 3, 1],
       [0, 2, 0, 9],
       [8, 8, 3, 2],
       [3, 7, 7, 6]])

In [56]:
np.sort(X)

array([[1, 3, 5, 8],
       [0, 0, 2, 9],
       [2, 3, 8, 8],
       [3, 6, 7, 7]])

In [57]:
np.sort(X, axis=1)

array([[1, 3, 5, 8],
       [0, 0, 2, 9],
       [2, 3, 8, 8],
       [3, 6, 7, 7]])

In [58]:
np.sort(X, axis=0)

array([[0, 2, 0, 1],
       [3, 7, 3, 2],
       [5, 8, 3, 6],
       [8, 8, 7, 9]])

In [59]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
np.random.shuffle(x)

In [61]:
x

array([ 2,  9,  3,  7,  4, 13,  1,  6,  0, 14, 12, 15,  5, 11, 10,  8])

In [62]:
# 返回的索引
np.argsort(x)

array([ 8,  6,  0,  2,  4, 12,  7,  3, 15,  1, 14, 13, 10,  5,  9, 11],
      dtype=int64)

In [63]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  9, 13, 14, 12, 15,  7, 11, 10,  8])

In [64]:
np.argpartition(x, 3)

array([ 8,  6,  0,  2,  4, 12,  7,  1,  5,  9, 10, 11,  3, 13, 14, 15],
      dtype=int64)

In [65]:
X

array([[5, 8, 3, 1],
       [0, 2, 0, 9],
       [8, 8, 3, 2],
       [3, 7, 7, 6]])

In [66]:
np.argsort(X, axis=1)

array([[3, 2, 0, 1],
       [0, 2, 1, 3],
       [3, 2, 0, 1],
       [0, 3, 1, 2]], dtype=int64)

In [67]:
np.argsort(X, axis=0)

array([[1, 1, 1, 0],
       [3, 3, 0, 2],
       [0, 0, 2, 3],
       [2, 2, 3, 1]], dtype=int64)

In [69]:
np.argpartition(X, 2, axis=1)

array([[3, 2, 0, 1],
       [0, 2, 1, 3],
       [3, 2, 1, 0],
       [0, 3, 2, 1]], dtype=int64)

In [70]:
np.argpartition(X, 2, axis=0)

array([[1, 1, 1, 0],
       [3, 3, 0, 2],
       [0, 2, 2, 3],
       [2, 0, 3, 1]], dtype=int64)